name = "portfolio-visits"
main = "visits.js"
compatibility_date = "2024-11-01"

# Substitua "id" pelo ID do namespace criado com:
#   npx wrangler kv namespace create VISITS
[[kv_namespaces]]
binding = "VISITS"
id = "501c17e351e846ef9c6985140464749f"
